# Generated by Django 3.2.25 on 2025-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CgpaApp', '0002_auto_20250625_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
